### ISSUE TITLE
cannot import name 'ScaleAdaptiveLogPolarEmb' from 'DBCAN.models.textrecog.decoders.Position_embedding

### ISSUE THREAD

**Issue by EternityWM** [Gaoxj2020/DBCAN#4]
hello,when I test this procedure,it cannot import name 'ScaleAdaptiveLogPolarEmb' from 'DBCAN.models.textrecog.decoders.Position_embedding,can you solve it?

**Comment by GaoXinJian-USTC** [comment]
将ScaleAdaptiveLogPolarEmb 改成 CBSAEmb试一下

**Comment by EternityWM** [comment]
非常感谢，非常感谢，跑了一下测试代码，可以成功。继续学习，运行一下。

**Comment by EternityWM** [comment]
非常感谢，非常感谢，跑了一下测试代码，可以成功。继续学习训练代码。
